//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BungieDatabaseClient.D2
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public long id { get; set; }
        public string username { get; set; }
        public string passwordhash { get; set; }
        public string BungieAccessToken { get; set; }
        public string BungieRefreshToken { get; set; }
        public string emailaddress { get; set; }
        public Nullable<System.DateTime> AuthorisedUntil { get; set; }
        public Nullable<System.DateTime> LastSeen { get; set; }
    }
}
